from elevator_environment import ElevatorEnvironment
from q_learning_agent import QLearningAgent


# ============================================================
# CONFIGURATION
# ============================================================

MODEL_PATH = "models/q_table.pkl"


# ============================================================
# CREATE ENVIRONMENT
# ============================================================

def create_environment():

    return ElevatorEnvironment(
        floors=10,
        number_of_elevators=3,
        capacities=[
            500,
            500,
            500
        ]
    )


# ============================================================
# TEST TRAINED RL AGENT
# ============================================================

def test_trained_agent():

    print()
    print("=" * 70)
    print("              TESTING TRAINED RL AGENT")
    print("=" * 70)

    # --------------------------------------------------------
    # Create environment
    # --------------------------------------------------------

    env = create_environment()

    # --------------------------------------------------------
    # Create agent object
    # --------------------------------------------------------
    #
    # This does NOT mean we are creating a new untrained model.
    #
    # The trained Q-table will be loaded immediately below.
    # --------------------------------------------------------

    agent = QLearningAgent()

    # --------------------------------------------------------
    # LOAD TRAINED MODEL
    # --------------------------------------------------------

    print()
    print("Loading trained Q-table...")

    agent.load(MODEL_PATH)

    # --------------------------------------------------------
    # Disable exploration
    # --------------------------------------------------------
    #
    # During testing:
    #
    # epsilon = 0
    #
    # Therefore the agent uses learned Q-values instead of
    # randomly exploring.
    # --------------------------------------------------------

    agent.set_evaluation_mode()

    print()
    print("Evaluation mode enabled.")
    print("Epsilon:", agent.epsilon)

    # ========================================================
    # CREATE PEAK DEMAND
    # ========================================================

    print()
    print("Creating peak-demand scenario...")

    state = env.generate_peak_demand()

    # Number of passengers generated by peak demand
    total_passengers = len(env.passengers)

    print(
        f"Passengers generated: {total_passengers}"
    )

    print("=" * 70)

    # ========================================================
    # TEST LOOP
    # ========================================================

    done = False

    total_reward = 0

    while not done:

        # ----------------------------------------------------
        # Get safe elevators
        # ----------------------------------------------------

        valid_actions = env.get_valid_actions()

        # ----------------------------------------------------
        # No safe elevator
        # ----------------------------------------------------

        if not valid_actions:

            print()
            print("No safe elevator available.")
            break

        # ----------------------------------------------------
        # Select learned action
        # ----------------------------------------------------

        action = agent.choose_action(
            state,
            valid_actions
        )

        if action is None:

            print()
            print("Agent could not select an action.")
            break

        # ----------------------------------------------------
        # Execute action
        # ----------------------------------------------------

        (
            next_state,
            reward,
            done,
            info
        ) = env.step(action)

        # ----------------------------------------------------
        # Display decision
        # ----------------------------------------------------

        print()
        print("-" * 70)

        print(
            f"Passenger ID      : P{info['passenger_id']}"
        )

        print(
            f"Selected Elevator : "
            f"{info['elevator']}"
        )

        print(
            f"Waiting Time      : "
            f"{info['waiting_time']} floors"
        )

        print(
            f"Travel Distance   : "
            f"{info['travel_distance']} floors"
        )

        print(
            f"Reward            : "
            f"{reward:.2f}"
        )

        print(
            f"Safety            : "
            f"{'SAFE' if info['safe'] else 'UNSAFE'}"
        )

        # ----------------------------------------------------
        # Add reward
        # ----------------------------------------------------

        total_reward += reward

        # ----------------------------------------------------
        # Move to next state
        # ----------------------------------------------------

        state = next_state

    # ========================================================
    # CALCULATE RESULTS
    # ========================================================

    if env.total_served > 0:

        average_waiting = (
            env.total_waiting_time
            / env.total_served
        )

    else:

        average_waiting = 0

    # ========================================================
    # DISPLAY FINAL RESULTS
    # ========================================================

    print()
    print("=" * 70)
    print("                 RL TEST RESULTS")
    print("=" * 70)

    print(
        f"Total Reward       : "
        f"{total_reward:.2f}"
    )

    print(
        f"People Generated   : "
        f"{total_passengers}"
    )

    print(
        f"People Served      : "
        f"{env.total_served}"
    )

    print(
        f"Average Waiting    : "
        f"{average_waiting:.2f} floors"
    )

    print(
        f"Total Distance     : "
        f"{env.total_distance} floors"
    )

    print(
        f"Overload Attempts  : "
        f"{env.overload_attempts}"
    )

    print(
        f"Safety Violations  : "
        f"{env.safety_violations}"
    )

    print(
        f"Learned States     : "
        f"{agent.number_of_states()}"
    )

    print("=" * 70)

    return {
        "total_reward": total_reward,
        "people_generated": total_passengers,
        "people_served": env.total_served,
        "average_waiting": average_waiting,
        "total_distance": env.total_distance,
        "overload_attempts": env.overload_attempts,
        "safety_violations": env.safety_violations
    }


# ============================================================
# MAIN
# ============================================================

if __name__ == "__main__":

    results = test_trained_agent()

    print()
    print("=" * 70)
    print("             RL TESTING COMPLETED")
    print("=" * 70)